export { mockSuggestionsDatabase, getSearchSuggestions, type MockResult } from './searchSuggestions'
export { mockSearchResults, searchResources, sortSearchResults, type SortOption, type SortDirection } from './searchResults'
export { mockDetailResources, getDetailResource } from './detailResources'
export { mockFilters, getFilters } from './filters'
export { httpService, type ApiResponse, type ApiError, type SearchParams, type DetailParams, type SuggestionParams } from './httpService'